name: 'DuckDB'
description: 'Powerful and fast SQL processing'
inputs:
  database-name:  # id of input
    description: 'Database name'
    required: false
    default: 'duck.db'
  script:
    description: 'Script to be executed'
    required: true
  extensions:
    description: 'Extensions to be loaded'
    required: false
    default: ''
  unsigned:
    description: 'Allow unsiged extensions'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [ ${{ runner.os }} = "Linux" ]; then
            if [ ! -f '/usr/local/bin/duckdb' ]; then
                wget -q https://github.com/duckdb/duckdb/releases/download/v0.8.1/duckdb_cli-linux-amd64.zip
                unzip duckdb_cli-linux-amd64.zip
                rm duckdb_cli-linux-amd64.zip
                chmod +x duckdb
                mv duckdb /usr/local/bin/
            fi
        elif [ ${{ runner.os }} = "macOS" ]; then
            if [ ! -f '/usr/local/bin/duckdb' ]; then
                wget -q https://github.com/duckdb/duckdb/releases/download/v0.8.1/duckdb_cli-osx-universal.zip
                unzip duckdb_cli-osx-universal.zip
                rm duckdb_cli-osx-universal.zip
                chmod +x duckdb
                mv duckdb /usr/local/bin/
            fi
        elif [ ${{ runner.os }} = "Windows" ]; then
            if [ ! -f 'C:/Program\ Files/duckdb.exe' ]; then
                C:/msys64/usr/bin/wget.exe -q https://github.com/duckdb/duckdb/releases/download/v0.8.1/duckdb_cli-windows-amd64.zip
                unzip duckdb_cli-windows-amd64.zip
                rm duckdb_cli-windows-amd64.zip
                chmod +x duckdb.exe
                mv duckdb.exe C:/Program\ Files/
            fi
        fi
    - shell: bash
      env:
        SCRIPT: ${{ inputs.script}}
        DB_NAME: ${{ inputs.database-name }}
        EXTENSIONS: ${{ inputs.extensions }}
        UNSIGNED: ${{ inputs.unsigned }}
      run: |
        EXTENSIONS_COMMAND=";"
        for filename in `echo $EXTENSIONS`; do
          EXTENSIONS_COMMAND+="INSTALL $filename; LOAD $filename;"
        done
        if ($UNSIGNED); then
            if [ ${{ runner.os }} = "Windows" ]; then
                C:/Program\ Files/duckdb.exe $DB_NAME -unsigned -c "$EXTENSIONS_COMMAND" -c "$SCRIPT"
            else
                duckdb $DB_NAME -unsigned -c "$EXTENSIONS_COMMAND" -c "$SCRIPT"
            fi
        else
            if [ ${{ runner.os }} = "Windows" ]; then
                C:/Program\ Files/duckdb.exe $DB_NAME -c "$EXTENSIONS_COMMAND" -c "$SCRIPT"
            else
                duckdb $DB_NAME -c "$EXTENSIONS_COMMAND" -c "$SCRIPT"
            fi
        fi
