name: 'DuckDB'
description: 'Powerful and fast SQL processing'
inputs:
  database-name:  # id of input
    description: 'Database name'
    required: false
    default: 'duck.db'
  script:
    description: 'Script to be executed'
    required: true
  extensions:
    description: 'Extensions to be loaded'
    required: false
    default: ''
  unsigned:
    description: 'Allow unsiged extensions'
    required: false
    default: 'false'
  version:
    description: 'DuckDB version to download, either latest or a tag'
    required: false
    default: 'v0.8.1'
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        if [ ${{ runner.os }} = "Linux" ]; then
            if [ ! -f '/usr/local/bin/duckdb_${VERSION}' ]; then
                if [ ${VERSION} = "latest" ]; then
                    wget -q wget https://carlopi.github.io/duckdb-latest/duckdb_cli-linux-amd64.zip
                else
                    wget -q https://github.com/duckdb/duckdb/releases/download/${VERSION}/duckdb_cli-linux-amd64.zip
                fi
                unzip duckdb_cli-linux-amd64.zip
                rm duckdb_cli-linux-amd64.zip
                chmod +x duckdb
                mv duckdb /usr/local/bin/duckdb_${VERSION}
            fi
        elif [ ${{ runner.os }} = "macOS" ]; then
            if [ ! -f '/usr/local/bin/duckdb_${VERSION}' ]; then
                if [ ${VERSION} = "latest" ]; then
                    wget -q wget https://carlopi.github.io/duckdb-latest/duckdb_cli-osx-universal.zip
                else
                    wget -q https://github.com/duckdb/duckdb/releases/download/${VERSION}/duckdb_cli-osx-universal.zip
                fi
                unzip duckdb_cli-osx-universal.zip
                rm duckdb_cli-osx-universal.zip
                chmod +x duckdb
                mv duckdb /usr/local/bin/duckdb_${VERSION}
            fi
        elif [ ${{ runner.os }} = "Windows" ]; then
            if [ ! -f 'C:/Program\ Files/duckdb_${VERSION}.exe' ]; then
                if [ ${VERSION} = "latest" ]; then
                    C:/msys64/usr/bin/wget.exe -q wget https://carlopi.github.io/duckdb-latest/duckdb_cli-windows-amd64.zip
                else
                    C:/msys64/usr/bin/wget.exe -q https://github.com/duckdb/duckdb/releases/download/${VERSION}/duckdb_cli-windows-amd64.zip
                fi
                unzip duckdb_cli-windows-amd64.zip
                rm duckdb_cli-windows-amd64.zip
                chmod +x duckdb.exe
                mv duckdb.exe C:/Program\ Files/duckdb_${VERSION}.exe
            fi
        fi
    - shell: bash
      env:
        VERSION: ${{ inputs.version }}
        SCRIPT: ${{ inputs.script}}
        DB_NAME: ${{ inputs.database-name }}
        EXTENSIONS: ${{ inputs.extensions }}
        UNSIGNED: ${{ inputs.unsigned }}
      run: |
        EXTENSIONS_COMMAND=";"
        for filename in `echo $EXTENSIONS`; do
          EXTENSIONS_COMMAND+="INSTALL $filename; LOAD $filename;"
        done
        if ($UNSIGNED); then
            if [ ${{ runner.os }} = "Windows" ]; then
                C:/Program\ Files/duckdb_${VERSION}.exe $DB_NAME -unsigned -c "$EXTENSIONS_COMMAND" -c "$SCRIPT"
            else
                duckdb_${VERSION} $DB_NAME -unsigned -c "$EXTENSIONS_COMMAND" -c "$SCRIPT"
            fi
        else
            if [ ${{ runner.os }} = "Windows" ]; then
                C:/Program\ Files/duckdb_${VERSION}.exe $DB_NAME -c "$EXTENSIONS_COMMAND" -c "$SCRIPT"
            else
                duckdb_${VERSION} $DB_NAME -c "$EXTENSIONS_COMMAND" -c "$SCRIPT"
            fi
        fi
